import { Controller, Get, Post, Body, Patch, Param, Delete, UseGuards, UsePipes, ValidationPipe, HttpCode, Req } from '@nestjs/common';
import { PublicService } from './public.service';
import { CreatePublicDto } from './dto/create-public.dto';
import { UpdatePublicDto } from './dto/update-public.dto';
import { InvitadosService } from 'src/invitados/invitados.service';
import { UtilidadesService } from 'src/utilidades/utilidades.service';



//import * as moment from 'moment';
//import 'moment/locale/pt-br';

const moment = require('moment');

import { v4 as uuidv4 } from 'uuid';
import { ApiBearerAuth, ApiTags } from '@nestjs/swagger';
import * as express from 'express';
import { JwtGuardGuard } from 'src/guards/jwt-guard/jwt-guard.guard';
import { CreateInvitadoPublicoDto } from './dto/invitado-publico.dto';
import { UpdateInvitadoDto } from './dto/invitado-actualizar-publico.dto';



// Para activar el auth JwTokenAuth
// @UseGuards( JwtGuardGuard )

@ApiTags('Datos')
@ApiBearerAuth()
@UsePipes( new ValidationPipe )



@Controller('public')
export class PublicController {
  constructor(
    private readonly publicService : PublicService , 
    private readonly srvInvitados  : InvitadosService , 
    private readonly util          : UtilidadesService , 
  ) {}
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  @Post('cancelar-asistencia')
  @HttpCode(200)
  async handleRechazarAsistencia( @Body('uuID') uuID : string ) {
    return this.srvInvitados.cancelarAsistencia( uuID );
  }
  // ................................................................
  // ................................................................
  @Post('confirmar-asistencia')
  @HttpCode(200)
  async handleCOnfirmarAsistencia( @Body('uuID') uuID : string ) {
    return this.srvInvitados.confirmarAsistencia( uuID );
  }
  // ................................................................
  // ................................................................
  @Post('get-invitado')
  @HttpCode(200)
  create( @Body('uuID') uuID : string ) {
    return this.srvInvitados.getInvitado( uuID );
  }
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  @Post('guardar-invitado')
  @HttpCode(200)
  async guardarInvitado( @Body() dto : CreateInvitadoPublicoDto ) {
    
    const createdAt   = moment().format('YYYY-MM-DD HH:mm:ss');

    const bodyProocolo = {
      ...dto , 
      created_at : createdAt , 
      updated_at : createdAt , 
    };

    return this.srvInvitados.guardar_invitado_extra( bodyProocolo );
  }
  // ................................................................
  // ................................................................
  @Patch('actualizar-invitado/:uuid')
  @HttpCode(200)
  async Actualizar( @Param('uuid') uuid : string, @Body() dto : UpdateInvitadoDto , @Req() req : express.Request ) {
    
    const createdAt   = moment().format('YYYY-MM-DD HH:mm:ss');

    const bodyProocolo = {
      ...dto , 
      updated_at : createdAt , 
    };
    return this.srvInvitados.ActualizarInvitado( uuid , bodyProocolo );
  }
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
  // ................................................................
}
// ...................................................................
function varDump( e ){
  console.log( e );
}
// ...................................................................
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
// ...................................................................
function Dump1( e , color )
{
// rojo, verde, amarillo, negrita_verde, negrita_verde_u
switch ( color ) {
    case 'rojo':
    console.log(  e.red );
    break;
    case 'verde':
    console.log(  e.green );
    break;
    case 'amarillo':
    console.log(  e.yellow );
    break;
    case 'negrita_verde':
    console.log(  e.green );
    break;
    case 'negrita_verde_u':
    console.log(  e.green.bold );
    break;
    default:
    //
    break;
}
}
// ..............................................................................